<a href="https://colab.research.google.com/github/tawaqalt/arbritrary/blob/master/Implementation_of_matrix_product_Tawakalitu_yusuf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Problem 1** is done manually by hand

$$A = \begin{bmatrix} -1 & 2 & 3 \\ 4 & -5 & 6 \\ 7 & 8 & -9 \end{bmatrix}$$, $$B = \begin{bmatrix} 0 & 2 & 1 \\ 0 & 2 & -8 \\ 2 & 9 & 8 \end{bmatrix}$$,
$$AB =\begin{bmatrix} 0+0+6 & -2+4+27 & -1-16-3 \\ 0+0+12 & 8-10+54 & 4+40-6 \\ 0+0-18 & 14+16-81 & 7-64+9 \end{bmatrix}$$,
$$BA = \begin{bmatrix} 6 & 29 & -20 \\ 12 & 52 & 38 \\ -18 & -51 & -48\end{bmatrix}$$


## **Problem 2**

In [ ]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
new_array = np.matmul(a_ndarray, b_ndarray)
print(new_array)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## **Problem 3**

In [ ]:
import numpy as np
#Using matmul operator
D = [a_ndarray[0,:] * b_ndarray[:,0], a_ndarray[0,:] * b_ndarray[:,1], a_ndarray[0,:] * b_ndarray[:,2]]
E = [a_ndarray[1,:] * b_ndarray[:,0], a_ndarray[1,:] * b_ndarray[:,1], a_ndarray[1,:] * b_ndarray[:,2]]
F = [a_ndarray[2,:] * b_ndarray[:,0], a_ndarray[2,:] * b_ndarray[:,1], a_ndarray[2,:] * b_ndarray[:,2]]
D = np.sum(D,axis=1)
E = np.sum(E,axis=1)
F = np.sum(F,axis=1)
new_array = np.array([D, E, F])
print("\nUsing matmul function:")
print(new_array)

#using the dot operator
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
new_array1 = np.dot(a_ndarray, b_ndarray)
print("\nUsing dot function:")
print(new_array1)

#using the @ operator
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
new_array2 = a_ndarray @ b_ndarray
print("\nUsing @ operator:")
print(new_array2)



Using matmul function:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

Using dot function:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

Using @ operator:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [ ]:
def product_of_matrix(a,b):
  matrix_ab = np.empty([3,3])
  for row1 in range(a.shape[0]):
    for col1 in range(b.shape[1]):
        matrix_ab[row1, col1] = sum(a[row1,:] * b[:, col1])
  return matrix_ab
print(product_of_matrix(a_ndarray,b_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [ ]:
#Using the if statement to compare two arrays
import numpy as np
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
if np.array_equal(d_ndarray, e_ndarray):
  print("The two arrays are equal")
else:
  print("The two arrays are not equal")

The two arrays are not equal


In [79]:
#the transpose of the matrix
tr_array = np.transpose(d_ndarray)
print(product_of_matrix(tr_array,e_ndarray))

[[ 33. -28.   9.]
 [-48.  41.  -6.]
 [  9.  -6.  45.]]
