<a href="https://colab.research.google.com/github/tawaqalt/arbritrary/blob/master/Tawaakalitu_Yusuf_RNNipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#importing libraries
import numpy as np

### Problem 1] Simple Forward propagation implementation of RNN

In [3]:
class ScratchSimpleRNNClassifier:
  #initializing parameters
    def __init__(self, n_features, n_nodes, n_output, n_sequences, lr=0.01, random_state=None):
        np.random.seed(random_state)
        self.n_features = n_features
        self.n_nodes = n_nodes
        self.n_output = n_output
        self.n_sequences = n_sequences
        self.lr = lr

        #initializing weights and biases
        self.Wx = np.random.randn(n_features, n_nodes)
        self.Wh = np.random.randn(n_nodes, n_nodes)
        self.B = np.zeros(n_nodes)
        self.Wout = np.random.randn(n_nodes, n_output)
        self.Bout = np.zeros(n_output)

        #initializing forward propagation
    def forward(self, X):
        batch_size, n_sequences, n_features = X.shape
        self.h = np.zeros((batch_size, self.n_nodes))
        self.hs = np.zeros((batch_size, n_sequences, self.n_nodes))
        self.ys = np.zeros((batch_size, n_sequences, self.n_output))

        for t in range(n_sequences):
            xt = X[:, t, :]
            at = np.dot(xt, self.Wx) + np.dot(self.h, self.Wh) + self.B
            self.h = np.tanh(at)
            self.hs[:, t, :] = self.h
            self.ys[:, t, :] = self.softmax(np.dot(self.h, self.Wout) + self.Bout)

        return self.ys
        #initializng activation function

    def softmax(self, x):
        exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))
        return exp_x / np.sum(exp_x, axis=1, keepdims=True)

    def fit(self, X, y, epochs=10):
        for epoch in range(epochs):
            output = self.forward(X)

            pass

    def predict(self, X):
        output = self.forward(X)
        return np.argmax(output[:, -1, :], axis=1)

n_features = 4
n_nodes = 5
n_output = 3
n_sequences = 10
batch_size = 8

X = np.random.randn(batch_size, n_sequences, n_features)
y = np.random.randint(0, 3, (batch_size, n_sequences, n_output))

model = ScratchSimpleRNNClassifier(n_features, n_nodes, n_output, n_sequences)
output = model.forward(X)

print("Output shape:", output.shape)
print("Output:", output)


Output shape: (8, 10, 3)
Output: [[[0.53138623 0.2340954  0.23451837]
  [0.48396964 0.07434351 0.44168685]
  [0.16778918 0.65305308 0.17915774]
  [0.00934986 0.56317364 0.4274765 ]
  [0.53254342 0.17195434 0.29550223]
  [0.94803445 0.01628455 0.03568099]
  [0.32338651 0.38120933 0.29540416]
  [0.02444282 0.44281166 0.53274552]
  [0.02777117 0.19904281 0.77318602]
  [0.42607923 0.04980206 0.52411871]]

 [[0.67308638 0.2983584  0.02855522]
  [0.08096381 0.78407558 0.13496061]
  [0.40309722 0.11614018 0.4807626 ]
  [0.23906978 0.27527045 0.48565977]
  [0.18325098 0.0392981  0.77745092]
  [0.64451104 0.04279153 0.31269744]
  [0.11626363 0.62829042 0.25544595]
  [0.01543592 0.65266214 0.33190195]
  [0.02039204 0.61543278 0.36417518]
  [0.12937254 0.09316449 0.77746297]]

 [[0.43550137 0.52659589 0.03790274]
  [0.01132484 0.65263177 0.3360434 ]
  [0.04157398 0.20251915 0.75590687]
  [0.65460274 0.02604642 0.31935084]
  [0.48243091 0.08182255 0.43574653]
  [0.0163113  0.65794073 0.32574797]
 

### [Problem 2] Experiment of forward propagation with small sequence

In [4]:
#assigning values to the weights and biases
x = np.array([[[1, 2], [2, 3], [3, 4]]]) / 100
w_x = np.array([[1, 3, 5, 7], [3, 5, 7, 8]]) / 100
w_h = np.array([[1, 3, 5, 7], [2, 4, 6, 8], [3, 5, 7, 8], [4, 6, 8, 10]]) / 100
b = np.array([1, 1, 1, 1])

batch_size = x.shape[0]
n_sequences = x.shape[1]
n_features = x.shape[2]
n_nodes = w_x.shape[1]

h = np.zeros((batch_size, n_nodes))

for t in range(n_sequences):
    xt = x[:, t, :]
    at = np.dot(xt, w_x) + np.dot(h, w_h) + b
    h = np.tanh(at)

print("Final hidden state h:", h)

Final hidden state h: [[0.79494228 0.81839002 0.83939649 0.85584174]]


### [Problem 3] (Advance assignment) Implementation of backpropagation

In [5]:
#implementation of simple RNN
class ScratchSimpleRNNClassifier:
    def __init__(self, n_features, n_nodes, n_outputs, lr=0.01):
        self.n_features = n_features
        self.n_nodes = n_nodes
        self.n_outputs = n_outputs
        self.lr = lr
        # initialize weights and biases
        self.W_x = np.random.randn(n_features, n_nodes)
        self.W_h = np.random.randn(n_nodes, n_nodes)
        self.b = np.zeros(n_nodes)
        self.W_y = np.random.randn(n_nodes, n_outputs)
        self.b_y = np.zeros(n_outputs)
        # initialize forward propagation
    def forward(self, x):
        self.batch_size, self.n_sequences, self.n_features = x.shape
        self.h = np.zeros((self.batch_size, self.n_sequences + 1, self.n_nodes))

        for t in range(self.n_sequences):
            self.h[:, t + 1, :] = np.tanh(np.dot(x[:, t, :], self.W_x) + np.dot(self.h[:, t, :], self.W_h) + self.b)

        y = np.dot(self.h[:, -1, :], self.W_y) + self.b_y
        return y
        # initialize backward propagation
    def backward(self, x, y_true, y_pred):
        dW_x = np.zeros_like(self.W_x)
        dW_h = np.zeros_like(self.W_h)
        db = np.zeros_like(self.b)
        dW_y = np.zeros_like(self.W_y)
        db_y = np.zeros_like(self.b_y)

        dy = y_pred - y_true

        dW_y = np.dot(self.h[:, -1, :].T, dy) / self.batch_size
        db_y = np.sum(dy, axis=0) / self.batch_size

        dh = np.dot(dy, self.W_y.T)

        for t in reversed(range(self.n_sequences)):
            da = dh * (1 - self.h[:, t + 1, :] ** 2)
            dW_x += np.dot(x[:, t, :].T, da) / self.batch_size
            dW_h += np.dot(self.h[:, t, :].T, da) / self.batch_size
            db += np.sum(da, axis=0) / self.batch_size

            dh = np.dot(da, self.W_h.T)

        self.W_x -= self.lr * dW_x
        self.W_h -= self.lr * dW_h
        self.b -= self.lr * db
        self.W_y -= self.lr * dW_y
        self.b_y -= self.lr * db_y

    def fit(self, X, y, epochs=10):
        for epoch in range(epochs):
            y_pred = self.forward(X)
            self.backward(X, y, y_pred)
            loss = np.mean((y_pred - y) ** 2)
            print(f'Epoch {epoch + 1}/{epochs}, Loss: {loss:.4f}')

    def predict(self, X):
        y_pred = self.forward(X)
        return y_pred


x = np.array([[[1, 2], [2, 3], [3, 4]]]) / 100
y_true = np.array([[0.5]])

model = ScratchSimpleRNNClassifier(n_features=2, n_nodes=4, n_outputs=1, lr=0.01)
model.fit(x, y_true, epochs=10)

y_pred = model.predict(x)
print("Predicted output:", y_pred)

Epoch 1/10, Loss: 0.1967
Epoch 2/10, Loss: 0.0325
Epoch 3/10, Loss: 0.0059
Epoch 4/10, Loss: 0.0011
Epoch 5/10, Loss: 0.0002
Epoch 6/10, Loss: 0.0000
Epoch 7/10, Loss: 0.0000
Epoch 8/10, Loss: 0.0000
Epoch 9/10, Loss: 0.0000
Epoch 10/10, Loss: 0.0000
Predicted output: [[0.4998773]]
